// Generated by tools/gen_opcodes.py from tools/opcodes.json. Do not edit by hand.
// To change an instruction, edit the helpers in core/cpu.cpp or the generator,
// then run: python3 tools/gen_opcodes.py
//
// clang-format off

#include "core/cpu.h"
#include "core/opcode_info.h"

namespace core {

// Several opcodes share a body (the 11 undefined ones, for example); that is expected.
// NOLINTBEGIN(bugprone-branch-clone, readability-function-size)

void Cpu::execute(std::uint8_t opcode) {
    switch (opcode) {
        case 0x00:  // NOP
            break;
        case 0x01:  // LD BC, n16
            reg_.set_bc(fetch16());
            break;
        case 0x02:  // LD [BC], A
            write8(reg_.bc(), reg_.a);
            break;
        case 0x03:  // INC BC
            reg_.set_bc(inc16(reg_.bc()));
            break;
        case 0x04:  // INC B
            reg_.b = alu_inc(reg_.b);
            break;
        case 0x05:  // DEC B
            reg_.b = alu_dec(reg_.b);
            break;
        case 0x06:  // LD B, n8
            reg_.b = fetch8();
            break;
        case 0x07:  // RLCA
            rlca();
            break;
        case 0x08:  // LD [a16], SP
            ld_a16_sp();
            break;
        case 0x09:  // ADD HL, BC
            alu_add_hl(reg_.bc());
            break;
        case 0x0A:  // LD A, [BC]
            reg_.a = read8(reg_.bc());
            break;
        case 0x0B:  // DEC BC
            reg_.set_bc(dec16(reg_.bc()));
            break;
        case 0x0C:  // INC C
            reg_.c = alu_inc(reg_.c);
            break;
        case 0x0D:  // DEC C
            reg_.c = alu_dec(reg_.c);
            break;
        case 0x0E:  // LD C, n8
            reg_.c = fetch8();
            break;
        case 0x0F:  // RRCA
            rrca();
            break;
        case 0x10:  // STOP n8
            stop();
            break;
        case 0x11:  // LD DE, n16
            reg_.set_de(fetch16());
            break;
        case 0x12:  // LD [DE], A
            write8(reg_.de(), reg_.a);
            break;
        case 0x13:  // INC DE
            reg_.set_de(inc16(reg_.de()));
            break;
        case 0x14:  // INC D
            reg_.d = alu_inc(reg_.d);
            break;
        case 0x15:  // DEC D
            reg_.d = alu_dec(reg_.d);
            break;
        case 0x16:  // LD D, n8
            reg_.d = fetch8();
            break;
        case 0x17:  // RLA
            rla();
            break;
        case 0x18:  // JR e8
            jr(true);
            break;
        case 0x19:  // ADD HL, DE
            alu_add_hl(reg_.de());
            break;
        case 0x1A:  // LD A, [DE]
            reg_.a = read8(reg_.de());
            break;
        case 0x1B:  // DEC DE
            reg_.set_de(dec16(reg_.de()));
            break;
        case 0x1C:  // INC E
            reg_.e = alu_inc(reg_.e);
            break;
        case 0x1D:  // DEC E
            reg_.e = alu_dec(reg_.e);
            break;
        case 0x1E:  // LD E, n8
            reg_.e = fetch8();
            break;
        case 0x1F:  // RRA
            rra();
            break;
        case 0x20:  // JR NZ, e8
            jr(!reg_.flag(Flag::Z));
            break;
        case 0x21:  // LD HL, n16
            reg_.set_hl(fetch16());
            break;
        case 0x22:  // LD [HL+], A
            write8(hl_post_increment(), reg_.a);
            break;
        case 0x23:  // INC HL
            reg_.set_hl(inc16(reg_.hl()));
            break;
        case 0x24:  // INC H
            reg_.h = alu_inc(reg_.h);
            break;
        case 0x25:  // DEC H
            reg_.h = alu_dec(reg_.h);
            break;
        case 0x26:  // LD H, n8
            reg_.h = fetch8();
            break;
        case 0x27:  // DAA
            daa();
            break;
        case 0x28:  // JR Z, e8
            jr(reg_.flag(Flag::Z));
            break;
        case 0x29:  // ADD HL, HL
            alu_add_hl(reg_.hl());
            break;
        case 0x2A:  // LD A, [HL+]
            reg_.a = read8(hl_post_increment());
            break;
        case 0x2B:  // DEC HL
            reg_.set_hl(dec16(reg_.hl()));
            break;
        case 0x2C:  // INC L
            reg_.l = alu_inc(reg_.l);
            break;
        case 0x2D:  // DEC L
            reg_.l = alu_dec(reg_.l);
            break;
        case 0x2E:  // LD L, n8
            reg_.l = fetch8();
            break;
        case 0x2F:  // CPL
            cpl();
            break;
        case 0x30:  // JR NC, e8
            jr(!reg_.flag(Flag::C));
            break;
        case 0x31:  // LD SP, n16
            reg_.sp = fetch16();
            break;
        case 0x32:  // LD [HL-], A
            write8(hl_post_decrement(), reg_.a);
            break;
        case 0x33:  // INC SP
            reg_.sp = inc16(reg_.sp);
            break;
        case 0x34:  // INC [HL]
            write8(reg_.hl(), alu_inc(read8(reg_.hl())));
            break;
        case 0x35:  // DEC [HL]
            write8(reg_.hl(), alu_dec(read8(reg_.hl())));
            break;
        case 0x36:  // LD [HL], n8
            write8(reg_.hl(), fetch8());
            break;
        case 0x37:  // SCF
            scf();
            break;
        case 0x38:  // JR C, e8
            jr(reg_.flag(Flag::C));
            break;
        case 0x39:  // ADD HL, SP
            alu_add_hl(reg_.sp);
            break;
        case 0x3A:  // LD A, [HL-]
            reg_.a = read8(hl_post_decrement());
            break;
        case 0x3B:  // DEC SP
            reg_.sp = dec16(reg_.sp);
            break;
        case 0x3C:  // INC A
            reg_.a = alu_inc(reg_.a);
            break;
        case 0x3D:  // DEC A
            reg_.a = alu_dec(reg_.a);
            break;
        case 0x3E:  // LD A, n8
            reg_.a = fetch8();
            break;
        case 0x3F:  // CCF
            ccf();
            break;
        case 0x40:  // LD B, B
            reg_.b = reg_.b;
            break;
        case 0x41:  // LD B, C
            reg_.b = reg_.c;
            break;
        case 0x42:  // LD B, D
            reg_.b = reg_.d;
            break;
        case 0x43:  // LD B, E
            reg_.b = reg_.e;
            break;
        case 0x44:  // LD B, H
            reg_.b = reg_.h;
            break;
        case 0x45:  // LD B, L
            reg_.b = reg_.l;
            break;
        case 0x46:  // LD B, [HL]
            reg_.b = read8(reg_.hl());
            break;
        case 0x47:  // LD B, A
            reg_.b = reg_.a;
            break;
        case 0x48:  // LD C, B
            reg_.c = reg_.b;
            break;
        case 0x49:  // LD C, C
            reg_.c = reg_.c;
            break;
        case 0x4A:  // LD C, D
            reg_.c = reg_.d;
            break;
        case 0x4B:  // LD C, E
            reg_.c = reg_.e;
            break;
        case 0x4C:  // LD C, H
            reg_.c = reg_.h;
            break;
        case 0x4D:  // LD C, L
            reg_.c = reg_.l;
            break;
        case 0x4E:  // LD C, [HL]
            reg_.c = read8(reg_.hl());
            break;
        case 0x4F:  // LD C, A
            reg_.c = reg_.a;
            break;
        case 0x50:  // LD D, B
            reg_.d = reg_.b;
            break;
        case 0x51:  // LD D, C
            reg_.d = reg_.c;
            break;
        case 0x52:  // LD D, D
            reg_.d = reg_.d;
            break;
        case 0x53:  // LD D, E
            reg_.d = reg_.e;
            break;
        case 0x54:  // LD D, H
            reg_.d = reg_.h;
            break;
        case 0x55:  // LD D, L
            reg_.d = reg_.l;
            break;
        case 0x56:  // LD D, [HL]
            reg_.d = read8(reg_.hl());
            break;
        case 0x57:  // LD D, A
            reg_.d = reg_.a;
            break;
        case 0x58:  // LD E, B
            reg_.e = reg_.b;
            break;
        case 0x59:  // LD E, C
            reg_.e = reg_.c;
            break;
        case 0x5A:  // LD E, D
            reg_.e = reg_.d;
            break;
        case 0x5B:  // LD E, E
            reg_.e = reg_.e;
            break;
        case 0x5C:  // LD E, H
            reg_.e = reg_.h;
            break;
        case 0x5D:  // LD E, L
            reg_.e = reg_.l;
            break;
        case 0x5E:  // LD E, [HL]
            reg_.e = read8(reg_.hl());
            break;
        case 0x5F:  // LD E, A
            reg_.e = reg_.a;
            break;
        case 0x60:  // LD H, B
            reg_.h = reg_.b;
            break;
        case 0x61:  // LD H, C
            reg_.h = reg_.c;
            break;
        case 0x62:  // LD H, D
            reg_.h = reg_.d;
            break;
        case 0x63:  // LD H, E
            reg_.h = reg_.e;
            break;
        case 0x64:  // LD H, H
            reg_.h = reg_.h;
            break;
        case 0x65:  // LD H, L
            reg_.h = reg_.l;
            break;
        case 0x66:  // LD H, [HL]
            reg_.h = read8(reg_.hl());
            break;
        case 0x67:  // LD H, A
            reg_.h = reg_.a;
            break;
        case 0x68:  // LD L, B
            reg_.l = reg_.b;
            break;
        case 0x69:  // LD L, C
            reg_.l = reg_.c;
            break;
        case 0x6A:  // LD L, D
            reg_.l = reg_.d;
            break;
        case 0x6B:  // LD L, E
            reg_.l = reg_.e;
            break;
        case 0x6C:  // LD L, H
            reg_.l = reg_.h;
            break;
        case 0x6D:  // LD L, L
            reg_.l = reg_.l;
            break;
        case 0x6E:  // LD L, [HL]
            reg_.l = read8(reg_.hl());
            break;
        case 0x6F:  // LD L, A
            reg_.l = reg_.a;
            break;
        case 0x70:  // LD [HL], B
            write8(reg_.hl(), reg_.b);
            break;
        case 0x71:  // LD [HL], C
            write8(reg_.hl(), reg_.c);
            break;
        case 0x72:  // LD [HL], D
            write8(reg_.hl(), reg_.d);
            break;
        case 0x73:  // LD [HL], E
            write8(reg_.hl(), reg_.e);
            break;
        case 0x74:  // LD [HL], H
            write8(reg_.hl(), reg_.h);
            break;
        case 0x75:  // LD [HL], L
            write8(reg_.hl(), reg_.l);
            break;
        case 0x76:  // HALT
            halt();
            break;
        case 0x77:  // LD [HL], A
            write8(reg_.hl(), reg_.a);
            break;
        case 0x78:  // LD A, B
            reg_.a = reg_.b;
            break;
        case 0x79:  // LD A, C
            reg_.a = reg_.c;
            break;
        case 0x7A:  // LD A, D
            reg_.a = reg_.d;
            break;
        case 0x7B:  // LD A, E
            reg_.a = reg_.e;
            break;
        case 0x7C:  // LD A, H
            reg_.a = reg_.h;
            break;
        case 0x7D:  // LD A, L
            reg_.a = reg_.l;
            break;
        case 0x7E:  // LD A, [HL]
            reg_.a = read8(reg_.hl());
            break;
        case 0x7F:  // LD A, A
            reg_.a = reg_.a;
            break;
        case 0x80:  // ADD A, B
            alu_add(reg_.b);
            break;
        case 0x81:  // ADD A, C
            alu_add(reg_.c);
            break;
        case 0x82:  // ADD A, D
            alu_add(reg_.d);
            break;
        case 0x83:  // ADD A, E
            alu_add(reg_.e);
            break;
        case 0x84:  // ADD A, H
            alu_add(reg_.h);
            break;
        case 0x85:  // ADD A, L
            alu_add(reg_.l);
            break;
        case 0x86:  // ADD A, [HL]
            alu_add(read8(reg_.hl()));
            break;
        case 0x87:  // ADD A, A
            alu_add(reg_.a);
            break;
        case 0x88:  // ADC A, B
            alu_adc(reg_.b);
            break;
        case 0x89:  // ADC A, C
            alu_adc(reg_.c);
            break;
        case 0x8A:  // ADC A, D
            alu_adc(reg_.d);
            break;
        case 0x8B:  // ADC A, E
            alu_adc(reg_.e);
            break;
        case 0x8C:  // ADC A, H
            alu_adc(reg_.h);
            break;
        case 0x8D:  // ADC A, L
            alu_adc(reg_.l);
            break;
        case 0x8E:  // ADC A, [HL]
            alu_adc(read8(reg_.hl()));
            break;
        case 0x8F:  // ADC A, A
            alu_adc(reg_.a);
            break;
        case 0x90:  // SUB A, B
            alu_sub(reg_.b);
            break;
        case 0x91:  // SUB A, C
            alu_sub(reg_.c);
            break;
        case 0x92:  // SUB A, D
            alu_sub(reg_.d);
            break;
        case 0x93:  // SUB A, E
            alu_sub(reg_.e);
            break;
        case 0x94:  // SUB A, H
            alu_sub(reg_.h);
            break;
        case 0x95:  // SUB A, L
            alu_sub(reg_.l);
            break;
        case 0x96:  // SUB A, [HL]
            alu_sub(read8(reg_.hl()));
            break;
        case 0x97:  // SUB A, A
            alu_sub(reg_.a);
            break;
        case 0x98:  // SBC A, B
            alu_sbc(reg_.b);
            break;
        case 0x99:  // SBC A, C
            alu_sbc(reg_.c);
            break;
        case 0x9A:  // SBC A, D
            alu_sbc(reg_.d);
            break;
        case 0x9B:  // SBC A, E
            alu_sbc(reg_.e);
            break;
        case 0x9C:  // SBC A, H
            alu_sbc(reg_.h);
            break;
        case 0x9D:  // SBC A, L
            alu_sbc(reg_.l);
            break;
        case 0x9E:  // SBC A, [HL]
            alu_sbc(read8(reg_.hl()));
            break;
        case 0x9F:  // SBC A, A
            alu_sbc(reg_.a);
            break;
        case 0xA0:  // AND A, B
            alu_and(reg_.b);
            break;
        case 0xA1:  // AND A, C
            alu_and(reg_.c);
            break;
        case 0xA2:  // AND A, D
            alu_and(reg_.d);
            break;
        case 0xA3:  // AND A, E
            alu_and(reg_.e);
            break;
        case 0xA4:  // AND A, H
            alu_and(reg_.h);
            break;
        case 0xA5:  // AND A, L
            alu_and(reg_.l);
            break;
        case 0xA6:  // AND A, [HL]
            alu_and(read8(reg_.hl()));
            break;
        case 0xA7:  // AND A, A
            alu_and(reg_.a);
            break;
        case 0xA8:  // XOR A, B
            alu_xor(reg_.b);
            break;
        case 0xA9:  // XOR A, C
            alu_xor(reg_.c);
            break;
        case 0xAA:  // XOR A, D
            alu_xor(reg_.d);
            break;
        case 0xAB:  // XOR A, E
            alu_xor(reg_.e);
            break;
        case 0xAC:  // XOR A, H
            alu_xor(reg_.h);
            break;
        case 0xAD:  // XOR A, L
            alu_xor(reg_.l);
            break;
        case 0xAE:  // XOR A, [HL]
            alu_xor(read8(reg_.hl()));
            break;
        case 0xAF:  // XOR A, A
            alu_xor(reg_.a);
            break;
        case 0xB0:  // OR A, B
            alu_or(reg_.b);
            break;
        case 0xB1:  // OR A, C
            alu_or(reg_.c);
            break;
        case 0xB2:  // OR A, D
            alu_or(reg_.d);
            break;
        case 0xB3:  // OR A, E
            alu_or(reg_.e);
            break;
        case 0xB4:  // OR A, H
            alu_or(reg_.h);
            break;
        case 0xB5:  // OR A, L
            alu_or(reg_.l);
            break;
        case 0xB6:  // OR A, [HL]
            alu_or(read8(reg_.hl()));
            break;
        case 0xB7:  // OR A, A
            alu_or(reg_.a);
            break;
        case 0xB8:  // CP A, B
            alu_cp(reg_.b);
            break;
        case 0xB9:  // CP A, C
            alu_cp(reg_.c);
            break;
        case 0xBA:  // CP A, D
            alu_cp(reg_.d);
            break;
        case 0xBB:  // CP A, E
            alu_cp(reg_.e);
            break;
        case 0xBC:  // CP A, H
            alu_cp(reg_.h);
            break;
        case 0xBD:  // CP A, L
            alu_cp(reg_.l);
            break;
        case 0xBE:  // CP A, [HL]
            alu_cp(read8(reg_.hl()));
            break;
        case 0xBF:  // CP A, A
            alu_cp(reg_.a);
            break;
        case 0xC0:  // RET NZ
            ret_if(!reg_.flag(Flag::Z));
            break;
        case 0xC1:  // POP BC
            reg_.set_bc(pop16());
            break;
        case 0xC2:  // JP NZ, a16
            jp(!reg_.flag(Flag::Z));
            break;
        case 0xC3:  // JP a16
            jp(true);
            break;
        case 0xC4:  // CALL NZ, a16
            call(!reg_.flag(Flag::Z));
            break;
        case 0xC5:  // PUSH BC
            push(reg_.bc());
            break;
        case 0xC6:  // ADD A, n8
            alu_add(fetch8());
            break;
        case 0xC7:  // RST $00
            rst(0x00);
            break;
        case 0xC8:  // RET Z
            ret_if(reg_.flag(Flag::Z));
            break;
        case 0xC9:  // RET
            ret();
            break;
        case 0xCA:  // JP Z, a16
            jp(reg_.flag(Flag::Z));
            break;
        case 0xCB:  // PREFIX
            execute_cb(fetch8());
            break;
        case 0xCC:  // CALL Z, a16
            call(reg_.flag(Flag::Z));
            break;
        case 0xCD:  // CALL a16
            call(true);
            break;
        case 0xCE:  // ADC A, n8
            alu_adc(fetch8());
            break;
        case 0xCF:  // RST $08
            rst(0x08);
            break;
        case 0xD0:  // RET NC
            ret_if(!reg_.flag(Flag::C));
            break;
        case 0xD1:  // POP DE
            reg_.set_de(pop16());
            break;
        case 0xD2:  // JP NC, a16
            jp(!reg_.flag(Flag::C));
            break;
        case 0xD3:  // ILLEGAL
            locked_ = true;
            break;
        case 0xD4:  // CALL NC, a16
            call(!reg_.flag(Flag::C));
            break;
        case 0xD5:  // PUSH DE
            push(reg_.de());
            break;
        case 0xD6:  // SUB A, n8
            alu_sub(fetch8());
            break;
        case 0xD7:  // RST $10
            rst(0x10);
            break;
        case 0xD8:  // RET C
            ret_if(reg_.flag(Flag::C));
            break;
        case 0xD9:  // RETI
            reti();
            break;
        case 0xDA:  // JP C, a16
            jp(reg_.flag(Flag::C));
            break;
        case 0xDB:  // ILLEGAL
            locked_ = true;
            break;
        case 0xDC:  // CALL C, a16
            call(reg_.flag(Flag::C));
            break;
        case 0xDD:  // ILLEGAL
            locked_ = true;
            break;
        case 0xDE:  // SBC A, n8
            alu_sbc(fetch8());
            break;
        case 0xDF:  // RST $18
            rst(0x18);
            break;
        case 0xE0:  // LDH [a8], A
            write8(high_page(fetch8()), reg_.a);
            break;
        case 0xE1:  // POP HL
            reg_.set_hl(pop16());
            break;
        case 0xE2:  // LDH [C], A
            write8(high_page(reg_.c), reg_.a);
            break;
        case 0xE3:  // ILLEGAL
            locked_ = true;
            break;
        case 0xE4:  // ILLEGAL
            locked_ = true;
            break;
        case 0xE5:  // PUSH HL
            push(reg_.hl());
            break;
        case 0xE6:  // AND A, n8
            alu_and(fetch8());
            break;
        case 0xE7:  // RST $20
            rst(0x20);
            break;
        case 0xE8:  // ADD SP, e8
            reg_.sp = sp_plus_offset();
            internal_cycle();
            internal_cycle();
            break;
        case 0xE9:  // JP HL
            reg_.pc = reg_.hl();
            break;
        case 0xEA:  // LD [a16], A
            write8(fetch16(), reg_.a);
            break;
        case 0xEB:  // ILLEGAL
            locked_ = true;
            break;
        case 0xEC:  // ILLEGAL
            locked_ = true;
            break;
        case 0xED:  // ILLEGAL
            locked_ = true;
            break;
        case 0xEE:  // XOR A, n8
            alu_xor(fetch8());
            break;
        case 0xEF:  // RST $28
            rst(0x28);
            break;
        case 0xF0:  // LDH A, [a8]
            reg_.a = read8(high_page(fetch8()));
            break;
        case 0xF1:  // POP AF
            reg_.set_af(pop16());
            break;
        case 0xF2:  // LDH A, [C]
            reg_.a = read8(high_page(reg_.c));
            break;
        case 0xF3:  // DI
            di();
            break;
        case 0xF4:  // ILLEGAL
            locked_ = true;
            break;
        case 0xF5:  // PUSH AF
            push(reg_.af());
            break;
        case 0xF6:  // OR A, n8
            alu_or(fetch8());
            break;
        case 0xF7:  // RST $30
            rst(0x30);
            break;
        case 0xF8:  // LD HL, SP+e8
            reg_.set_hl(sp_plus_offset());
            internal_cycle();
            break;
        case 0xF9:  // LD SP, HL
            reg_.sp = reg_.hl();
            internal_cycle();
            break;
        case 0xFA:  // LD A, [a16]
            reg_.a = read8(fetch16());
            break;
        case 0xFB:  // EI
            ei();
            break;
        case 0xFC:  // ILLEGAL
            locked_ = true;
            break;
        case 0xFD:  // ILLEGAL
            locked_ = true;
            break;
        case 0xFE:  // CP A, n8
            alu_cp(fetch8());
            break;
        case 0xFF:  // RST $38
            rst(0x38);
            break;
        default:
            break;
    }
}

void Cpu::execute_cb(std::uint8_t opcode) {
    switch (opcode) {
        case 0x00:  // RLC B
            reg_.b = alu_rlc(reg_.b);
            break;
        case 0x01:  // RLC C
            reg_.c = alu_rlc(reg_.c);
            break;
        case 0x02:  // RLC D
            reg_.d = alu_rlc(reg_.d);
            break;
        case 0x03:  // RLC E
            reg_.e = alu_rlc(reg_.e);
            break;
        case 0x04:  // RLC H
            reg_.h = alu_rlc(reg_.h);
            break;
        case 0x05:  // RLC L
            reg_.l = alu_rlc(reg_.l);
            break;
        case 0x06:  // RLC [HL]
            write8(reg_.hl(), alu_rlc(read8(reg_.hl())));
            break;
        case 0x07:  // RLC A
            reg_.a = alu_rlc(reg_.a);
            break;
        case 0x08:  // RRC B
            reg_.b = alu_rrc(reg_.b);
            break;
        case 0x09:  // RRC C
            reg_.c = alu_rrc(reg_.c);
            break;
        case 0x0A:  // RRC D
            reg_.d = alu_rrc(reg_.d);
            break;
        case 0x0B:  // RRC E
            reg_.e = alu_rrc(reg_.e);
            break;
        case 0x0C:  // RRC H
            reg_.h = alu_rrc(reg_.h);
            break;
        case 0x0D:  // RRC L
            reg_.l = alu_rrc(reg_.l);
            break;
        case 0x0E:  // RRC [HL]
            write8(reg_.hl(), alu_rrc(read8(reg_.hl())));
            break;
        case 0x0F:  // RRC A
            reg_.a = alu_rrc(reg_.a);
            break;
        case 0x10:  // RL B
            reg_.b = alu_rl(reg_.b);
            break;
        case 0x11:  // RL C
            reg_.c = alu_rl(reg_.c);
            break;
        case 0x12:  // RL D
            reg_.d = alu_rl(reg_.d);
            break;
        case 0x13:  // RL E
            reg_.e = alu_rl(reg_.e);
            break;
        case 0x14:  // RL H
            reg_.h = alu_rl(reg_.h);
            break;
        case 0x15:  // RL L
            reg_.l = alu_rl(reg_.l);
            break;
        case 0x16:  // RL [HL]
            write8(reg_.hl(), alu_rl(read8(reg_.hl())));
            break;
        case 0x17:  // RL A
            reg_.a = alu_rl(reg_.a);
            break;
        case 0x18:  // RR B
            reg_.b = alu_rr(reg_.b);
            break;
        case 0x19:  // RR C
            reg_.c = alu_rr(reg_.c);
            break;
        case 0x1A:  // RR D
            reg_.d = alu_rr(reg_.d);
            break;
        case 0x1B:  // RR E
            reg_.e = alu_rr(reg_.e);
            break;
        case 0x1C:  // RR H
            reg_.h = alu_rr(reg_.h);
            break;
        case 0x1D:  // RR L
            reg_.l = alu_rr(reg_.l);
            break;
        case 0x1E:  // RR [HL]
            write8(reg_.hl(), alu_rr(read8(reg_.hl())));
            break;
        case 0x1F:  // RR A
            reg_.a = alu_rr(reg_.a);
            break;
        case 0x20:  // SLA B
            reg_.b = alu_sla(reg_.b);
            break;
        case 0x21:  // SLA C
            reg_.c = alu_sla(reg_.c);
            break;
        case 0x22:  // SLA D
            reg_.d = alu_sla(reg_.d);
            break;
        case 0x23:  // SLA E
            reg_.e = alu_sla(reg_.e);
            break;
        case 0x24:  // SLA H
            reg_.h = alu_sla(reg_.h);
            break;
        case 0x25:  // SLA L
            reg_.l = alu_sla(reg_.l);
            break;
        case 0x26:  // SLA [HL]
            write8(reg_.hl(), alu_sla(read8(reg_.hl())));
            break;
        case 0x27:  // SLA A
            reg_.a = alu_sla(reg_.a);
            break;
        case 0x28:  // SRA B
            reg_.b = alu_sra(reg_.b);
            break;
        case 0x29:  // SRA C
            reg_.c = alu_sra(reg_.c);
            break;
        case 0x2A:  // SRA D
            reg_.d = alu_sra(reg_.d);
            break;
        case 0x2B:  // SRA E
            reg_.e = alu_sra(reg_.e);
            break;
        case 0x2C:  // SRA H
            reg_.h = alu_sra(reg_.h);
            break;
        case 0x2D:  // SRA L
            reg_.l = alu_sra(reg_.l);
            break;
        case 0x2E:  // SRA [HL]
            write8(reg_.hl(), alu_sra(read8(reg_.hl())));
            break;
        case 0x2F:  // SRA A
            reg_.a = alu_sra(reg_.a);
            break;
        case 0x30:  // SWAP B
            reg_.b = alu_swap(reg_.b);
            break;
        case 0x31:  // SWAP C
            reg_.c = alu_swap(reg_.c);
            break;
        case 0x32:  // SWAP D
            reg_.d = alu_swap(reg_.d);
            break;
        case 0x33:  // SWAP E
            reg_.e = alu_swap(reg_.e);
            break;
        case 0x34:  // SWAP H
            reg_.h = alu_swap(reg_.h);
            break;
        case 0x35:  // SWAP L
            reg_.l = alu_swap(reg_.l);
            break;
        case 0x36:  // SWAP [HL]
            write8(reg_.hl(), alu_swap(read8(reg_.hl())));
            break;
        case 0x37:  // SWAP A
            reg_.a = alu_swap(reg_.a);
            break;
        case 0x38:  // SRL B
            reg_.b = alu_srl(reg_.b);
            break;
        case 0x39:  // SRL C
            reg_.c = alu_srl(reg_.c);
            break;
        case 0x3A:  // SRL D
            reg_.d = alu_srl(reg_.d);
            break;
        case 0x3B:  // SRL E
            reg_.e = alu_srl(reg_.e);
            break;
        case 0x3C:  // SRL H
            reg_.h = alu_srl(reg_.h);
            break;
        case 0x3D:  // SRL L
            reg_.l = alu_srl(reg_.l);
            break;
        case 0x3E:  // SRL [HL]
            write8(reg_.hl(), alu_srl(read8(reg_.hl())));
            break;
        case 0x3F:  // SRL A
            reg_.a = alu_srl(reg_.a);
            break;
        case 0x40:  // BIT 0, B
            alu_bit(0, reg_.b);
            break;
        case 0x41:  // BIT 0, C
            alu_bit(0, reg_.c);
            break;
        case 0x42:  // BIT 0, D
            alu_bit(0, reg_.d);
            break;
        case 0x43:  // BIT 0, E
            alu_bit(0, reg_.e);
            break;
        case 0x44:  // BIT 0, H
            alu_bit(0, reg_.h);
            break;
        case 0x45:  // BIT 0, L
            alu_bit(0, reg_.l);
            break;
        case 0x46:  // BIT 0, [HL]
            alu_bit(0, read8(reg_.hl()));
            break;
        case 0x47:  // BIT 0, A
            alu_bit(0, reg_.a);
            break;
        case 0x48:  // BIT 1, B
            alu_bit(1, reg_.b);
            break;
        case 0x49:  // BIT 1, C
            alu_bit(1, reg_.c);
            break;
        case 0x4A:  // BIT 1, D
            alu_bit(1, reg_.d);
            break;
        case 0x4B:  // BIT 1, E
            alu_bit(1, reg_.e);
            break;
        case 0x4C:  // BIT 1, H
            alu_bit(1, reg_.h);
            break;
        case 0x4D:  // BIT 1, L
            alu_bit(1, reg_.l);
            break;
        case 0x4E:  // BIT 1, [HL]
            alu_bit(1, read8(reg_.hl()));
            break;
        case 0x4F:  // BIT 1, A
            alu_bit(1, reg_.a);
            break;
        case 0x50:  // BIT 2, B
            alu_bit(2, reg_.b);
            break;
        case 0x51:  // BIT 2, C
            alu_bit(2, reg_.c);
            break;
        case 0x52:  // BIT 2, D
            alu_bit(2, reg_.d);
            break;
        case 0x53:  // BIT 2, E
            alu_bit(2, reg_.e);
            break;
        case 0x54:  // BIT 2, H
            alu_bit(2, reg_.h);
            break;
        case 0x55:  // BIT 2, L
            alu_bit(2, reg_.l);
            break;
        case 0x56:  // BIT 2, [HL]
            alu_bit(2, read8(reg_.hl()));
            break;
        case 0x57:  // BIT 2, A
            alu_bit(2, reg_.a);
            break;
        case 0x58:  // BIT 3, B
            alu_bit(3, reg_.b);
            break;
        case 0x59:  // BIT 3, C
            alu_bit(3, reg_.c);
            break;
        case 0x5A:  // BIT 3, D
            alu_bit(3, reg_.d);
            break;
        case 0x5B:  // BIT 3, E
            alu_bit(3, reg_.e);
            break;
        case 0x5C:  // BIT 3, H
            alu_bit(3, reg_.h);
            break;
        case 0x5D:  // BIT 3, L
            alu_bit(3, reg_.l);
            break;
        case 0x5E:  // BIT 3, [HL]
            alu_bit(3, read8(reg_.hl()));
            break;
        case 0x5F:  // BIT 3, A
            alu_bit(3, reg_.a);
            break;
        case 0x60:  // BIT 4, B
            alu_bit(4, reg_.b);
            break;
        case 0x61:  // BIT 4, C
            alu_bit(4, reg_.c);
            break;
        case 0x62:  // BIT 4, D
            alu_bit(4, reg_.d);
            break;
        case 0x63:  // BIT 4, E
            alu_bit(4, reg_.e);
            break;
        case 0x64:  // BIT 4, H
            alu_bit(4, reg_.h);
            break;
        case 0x65:  // BIT 4, L
            alu_bit(4, reg_.l);
            break;
        case 0x66:  // BIT 4, [HL]
            alu_bit(4, read8(reg_.hl()));
            break;
        case 0x67:  // BIT 4, A
            alu_bit(4, reg_.a);
            break;
        case 0x68:  // BIT 5, B
            alu_bit(5, reg_.b);
            break;
        case 0x69:  // BIT 5, C
            alu_bit(5, reg_.c);
            break;
        case 0x6A:  // BIT 5, D
            alu_bit(5, reg_.d);
            break;
        case 0x6B:  // BIT 5, E
            alu_bit(5, reg_.e);
            break;
        case 0x6C:  // BIT 5, H
            alu_bit(5, reg_.h);
            break;
        case 0x6D:  // BIT 5, L
            alu_bit(5, reg_.l);
            break;
        case 0x6E:  // BIT 5, [HL]
            alu_bit(5, read8(reg_.hl()));
            break;
        case 0x6F:  // BIT 5, A
            alu_bit(5, reg_.a);
            break;
        case 0x70:  // BIT 6, B
            alu_bit(6, reg_.b);
            break;
        case 0x71:  // BIT 6, C
            alu_bit(6, reg_.c);
            break;
        case 0x72:  // BIT 6, D
            alu_bit(6, reg_.d);
            break;
        case 0x73:  // BIT 6, E
            alu_bit(6, reg_.e);
            break;
        case 0x74:  // BIT 6, H
            alu_bit(6, reg_.h);
            break;
        case 0x75:  // BIT 6, L
            alu_bit(6, reg_.l);
            break;
        case 0x76:  // BIT 6, [HL]
            alu_bit(6, read8(reg_.hl()));
            break;
        case 0x77:  // BIT 6, A
            alu_bit(6, reg_.a);
            break;
        case 0x78:  // BIT 7, B
            alu_bit(7, reg_.b);
            break;
        case 0x79:  // BIT 7, C
            alu_bit(7, reg_.c);
            break;
        case 0x7A:  // BIT 7, D
            alu_bit(7, reg_.d);
            break;
        case 0x7B:  // BIT 7, E
            alu_bit(7, reg_.e);
            break;
        case 0x7C:  // BIT 7, H
            alu_bit(7, reg_.h);
            break;
        case 0x7D:  // BIT 7, L
            alu_bit(7, reg_.l);
            break;
        case 0x7E:  // BIT 7, [HL]
            alu_bit(7, read8(reg_.hl()));
            break;
        case 0x7F:  // BIT 7, A
            alu_bit(7, reg_.a);
            break;
        case 0x80:  // RES 0, B
            reg_.b = res_bit(0, reg_.b);
            break;
        case 0x81:  // RES 0, C
            reg_.c = res_bit(0, reg_.c);
            break;
        case 0x82:  // RES 0, D
            reg_.d = res_bit(0, reg_.d);
            break;
        case 0x83:  // RES 0, E
            reg_.e = res_bit(0, reg_.e);
            break;
        case 0x84:  // RES 0, H
            reg_.h = res_bit(0, reg_.h);
            break;
        case 0x85:  // RES 0, L
            reg_.l = res_bit(0, reg_.l);
            break;
        case 0x86:  // RES 0, [HL]
            write8(reg_.hl(), res_bit(0, read8(reg_.hl())));
            break;
        case 0x87:  // RES 0, A
            reg_.a = res_bit(0, reg_.a);
            break;
        case 0x88:  // RES 1, B
            reg_.b = res_bit(1, reg_.b);
            break;
        case 0x89:  // RES 1, C
            reg_.c = res_bit(1, reg_.c);
            break;
        case 0x8A:  // RES 1, D
            reg_.d = res_bit(1, reg_.d);
            break;
        case 0x8B:  // RES 1, E
            reg_.e = res_bit(1, reg_.e);
            break;
        case 0x8C:  // RES 1, H
            reg_.h = res_bit(1, reg_.h);
            break;
        case 0x8D:  // RES 1, L
            reg_.l = res_bit(1, reg_.l);
            break;
        case 0x8E:  // RES 1, [HL]
            write8(reg_.hl(), res_bit(1, read8(reg_.hl())));
            break;
        case 0x8F:  // RES 1, A
            reg_.a = res_bit(1, reg_.a);
            break;
        case 0x90:  // RES 2, B
            reg_.b = res_bit(2, reg_.b);
            break;
        case 0x91:  // RES 2, C
            reg_.c = res_bit(2, reg_.c);
            break;
        case 0x92:  // RES 2, D
            reg_.d = res_bit(2, reg_.d);
            break;
        case 0x93:  // RES 2, E
            reg_.e = res_bit(2, reg_.e);
            break;
        case 0x94:  // RES 2, H
            reg_.h = res_bit(2, reg_.h);
            break;
        case 0x95:  // RES 2, L
            reg_.l = res_bit(2, reg_.l);
            break;
        case 0x96:  // RES 2, [HL]
            write8(reg_.hl(), res_bit(2, read8(reg_.hl())));
            break;
        case 0x97:  // RES 2, A
            reg_.a = res_bit(2, reg_.a);
            break;
        case 0x98:  // RES 3, B
            reg_.b = res_bit(3, reg_.b);
            break;
        case 0x99:  // RES 3, C
            reg_.c = res_bit(3, reg_.c);
            break;
        case 0x9A:  // RES 3, D
            reg_.d = res_bit(3, reg_.d);
            break;
        case 0x9B:  // RES 3, E
            reg_.e = res_bit(3, reg_.e);
            break;
        case 0x9C:  // RES 3, H
            reg_.h = res_bit(3, reg_.h);
            break;
        case 0x9D:  // RES 3, L
            reg_.l = res_bit(3, reg_.l);
            break;
        case 0x9E:  // RES 3, [HL]
            write8(reg_.hl(), res_bit(3, read8(reg_.hl())));
            break;
        case 0x9F:  // RES 3, A
            reg_.a = res_bit(3, reg_.a);
            break;
        case 0xA0:  // RES 4, B
            reg_.b = res_bit(4, reg_.b);
            break;
        case 0xA1:  // RES 4, C
            reg_.c = res_bit(4, reg_.c);
            break;
        case 0xA2:  // RES 4, D
            reg_.d = res_bit(4, reg_.d);
            break;
        case 0xA3:  // RES 4, E
            reg_.e = res_bit(4, reg_.e);
            break;
        case 0xA4:  // RES 4, H
            reg_.h = res_bit(4, reg_.h);
            break;
        case 0xA5:  // RES 4, L
            reg_.l = res_bit(4, reg_.l);
            break;
        case 0xA6:  // RES 4, [HL]
            write8(reg_.hl(), res_bit(4, read8(reg_.hl())));
            break;
        case 0xA7:  // RES 4, A
            reg_.a = res_bit(4, reg_.a);
            break;
        case 0xA8:  // RES 5, B
            reg_.b = res_bit(5, reg_.b);
            break;
        case 0xA9:  // RES 5, C
            reg_.c = res_bit(5, reg_.c);
            break;
        case 0xAA:  // RES 5, D
            reg_.d = res_bit(5, reg_.d);
            break;
        case 0xAB:  // RES 5, E
            reg_.e = res_bit(5, reg_.e);
            break;
        case 0xAC:  // RES 5, H
            reg_.h = res_bit(5, reg_.h);
            break;
        case 0xAD:  // RES 5, L
            reg_.l = res_bit(5, reg_.l);
            break;
        case 0xAE:  // RES 5, [HL]
            write8(reg_.hl(), res_bit(5, read8(reg_.hl())));
            break;
        case 0xAF:  // RES 5, A
            reg_.a = res_bit(5, reg_.a);
            break;
        case 0xB0:  // RES 6, B
            reg_.b = res_bit(6, reg_.b);
            break;
        case 0xB1:  // RES 6, C
            reg_.c = res_bit(6, reg_.c);
            break;
        case 0xB2:  // RES 6, D
            reg_.d = res_bit(6, reg_.d);
            break;
        case 0xB3:  // RES 6, E
            reg_.e = res_bit(6, reg_.e);
            break;
        case 0xB4:  // RES 6, H
            reg_.h = res_bit(6, reg_.h);
            break;
        case 0xB5:  // RES 6, L
            reg_.l = res_bit(6, reg_.l);
            break;
        case 0xB6:  // RES 6, [HL]
            write8(reg_.hl(), res_bit(6, read8(reg_.hl())));
            break;
        case 0xB7:  // RES 6, A
            reg_.a = res_bit(6, reg_.a);
            break;
        case 0xB8:  // RES 7, B
            reg_.b = res_bit(7, reg_.b);
            break;
        case 0xB9:  // RES 7, C
            reg_.c = res_bit(7, reg_.c);
            break;
        case 0xBA:  // RES 7, D
            reg_.d = res_bit(7, reg_.d);
            break;
        case 0xBB:  // RES 7, E
            reg_.e = res_bit(7, reg_.e);
            break;
        case 0xBC:  // RES 7, H
            reg_.h = res_bit(7, reg_.h);
            break;
        case 0xBD:  // RES 7, L
            reg_.l = res_bit(7, reg_.l);
            break;
        case 0xBE:  // RES 7, [HL]
            write8(reg_.hl(), res_bit(7, read8(reg_.hl())));
            break;
        case 0xBF:  // RES 7, A
            reg_.a = res_bit(7, reg_.a);
            break;
        case 0xC0:  // SET 0, B
            reg_.b = set_bit(0, reg_.b);
            break;
        case 0xC1:  // SET 0, C
            reg_.c = set_bit(0, reg_.c);
            break;
        case 0xC2:  // SET 0, D
            reg_.d = set_bit(0, reg_.d);
            break;
        case 0xC3:  // SET 0, E
            reg_.e = set_bit(0, reg_.e);
            break;
        case 0xC4:  // SET 0, H
            reg_.h = set_bit(0, reg_.h);
            break;
        case 0xC5:  // SET 0, L
            reg_.l = set_bit(0, reg_.l);
            break;
        case 0xC6:  // SET 0, [HL]
            write8(reg_.hl(), set_bit(0, read8(reg_.hl())));
            break;
        case 0xC7:  // SET 0, A
            reg_.a = set_bit(0, reg_.a);
            break;
        case 0xC8:  // SET 1, B
            reg_.b = set_bit(1, reg_.b);
            break;
        case 0xC9:  // SET 1, C
            reg_.c = set_bit(1, reg_.c);
            break;
        case 0xCA:  // SET 1, D
            reg_.d = set_bit(1, reg_.d);
            break;
        case 0xCB:  // SET 1, E
            reg_.e = set_bit(1, reg_.e);
            break;
        case 0xCC:  // SET 1, H
            reg_.h = set_bit(1, reg_.h);
            break;
        case 0xCD:  // SET 1, L
            reg_.l = set_bit(1, reg_.l);
            break;
        case 0xCE:  // SET 1, [HL]
            write8(reg_.hl(), set_bit(1, read8(reg_.hl())));
            break;
        case 0xCF:  // SET 1, A
            reg_.a = set_bit(1, reg_.a);
            break;
        case 0xD0:  // SET 2, B
            reg_.b = set_bit(2, reg_.b);
            break;
        case 0xD1:  // SET 2, C
            reg_.c = set_bit(2, reg_.c);
            break;
        case 0xD2:  // SET 2, D
            reg_.d = set_bit(2, reg_.d);
            break;
        case 0xD3:  // SET 2, E
            reg_.e = set_bit(2, reg_.e);
            break;
        case 0xD4:  // SET 2, H
            reg_.h = set_bit(2, reg_.h);
            break;
        case 0xD5:  // SET 2, L
            reg_.l = set_bit(2, reg_.l);
            break;
        case 0xD6:  // SET 2, [HL]
            write8(reg_.hl(), set_bit(2, read8(reg_.hl())));
            break;
        case 0xD7:  // SET 2, A
            reg_.a = set_bit(2, reg_.a);
            break;
        case 0xD8:  // SET 3, B
            reg_.b = set_bit(3, reg_.b);
            break;
        case 0xD9:  // SET 3, C
            reg_.c = set_bit(3, reg_.c);
            break;
        case 0xDA:  // SET 3, D
            reg_.d = set_bit(3, reg_.d);
            break;
        case 0xDB:  // SET 3, E
            reg_.e = set_bit(3, reg_.e);
            break;
        case 0xDC:  // SET 3, H
            reg_.h = set_bit(3, reg_.h);
            break;
        case 0xDD:  // SET 3, L
            reg_.l = set_bit(3, reg_.l);
            break;
        case 0xDE:  // SET 3, [HL]
            write8(reg_.hl(), set_bit(3, read8(reg_.hl())));
            break;
        case 0xDF:  // SET 3, A
            reg_.a = set_bit(3, reg_.a);
            break;
        case 0xE0:  // SET 4, B
            reg_.b = set_bit(4, reg_.b);
            break;
        case 0xE1:  // SET 4, C
            reg_.c = set_bit(4, reg_.c);
            break;
        case 0xE2:  // SET 4, D
            reg_.d = set_bit(4, reg_.d);
            break;
        case 0xE3:  // SET 4, E
            reg_.e = set_bit(4, reg_.e);
            break;
        case 0xE4:  // SET 4, H
            reg_.h = set_bit(4, reg_.h);
            break;
        case 0xE5:  // SET 4, L
            reg_.l = set_bit(4, reg_.l);
            break;
        case 0xE6:  // SET 4, [HL]
            write8(reg_.hl(), set_bit(4, read8(reg_.hl())));
            break;
        case 0xE7:  // SET 4, A
            reg_.a = set_bit(4, reg_.a);
            break;
        case 0xE8:  // SET 5, B
            reg_.b = set_bit(5, reg_.b);
            break;
        case 0xE9:  // SET 5, C
            reg_.c = set_bit(5, reg_.c);
            break;
        case 0xEA:  // SET 5, D
            reg_.d = set_bit(5, reg_.d);
            break;
        case 0xEB:  // SET 5, E
            reg_.e = set_bit(5, reg_.e);
            break;
        case 0xEC:  // SET 5, H
            reg_.h = set_bit(5, reg_.h);
            break;
        case 0xED:  // SET 5, L
            reg_.l = set_bit(5, reg_.l);
            break;
        case 0xEE:  // SET 5, [HL]
            write8(reg_.hl(), set_bit(5, read8(reg_.hl())));
            break;
        case 0xEF:  // SET 5, A
            reg_.a = set_bit(5, reg_.a);
            break;
        case 0xF0:  // SET 6, B
            reg_.b = set_bit(6, reg_.b);
            break;
        case 0xF1:  // SET 6, C
            reg_.c = set_bit(6, reg_.c);
            break;
        case 0xF2:  // SET 6, D
            reg_.d = set_bit(6, reg_.d);
            break;
        case 0xF3:  // SET 6, E
            reg_.e = set_bit(6, reg_.e);
            break;
        case 0xF4:  // SET 6, H
            reg_.h = set_bit(6, reg_.h);
            break;
        case 0xF5:  // SET 6, L
            reg_.l = set_bit(6, reg_.l);
            break;
        case 0xF6:  // SET 6, [HL]
            write8(reg_.hl(), set_bit(6, read8(reg_.hl())));
            break;
        case 0xF7:  // SET 6, A
            reg_.a = set_bit(6, reg_.a);
            break;
        case 0xF8:  // SET 7, B
            reg_.b = set_bit(7, reg_.b);
            break;
        case 0xF9:  // SET 7, C
            reg_.c = set_bit(7, reg_.c);
            break;
        case 0xFA:  // SET 7, D
            reg_.d = set_bit(7, reg_.d);
            break;
        case 0xFB:  // SET 7, E
            reg_.e = set_bit(7, reg_.e);
            break;
        case 0xFC:  // SET 7, H
            reg_.h = set_bit(7, reg_.h);
            break;
        case 0xFD:  // SET 7, L
            reg_.l = set_bit(7, reg_.l);
            break;
        case 0xFE:  // SET 7, [HL]
            write8(reg_.hl(), set_bit(7, read8(reg_.hl())));
            break;
        case 0xFF:  // SET 7, A
            reg_.a = set_bit(7, reg_.a);
            break;
        default:
            break;
    }
}

// NOLINTEND(bugprone-branch-clone, readability-function-size)

const std::array<OpcodeInfo, 256> kOpcodeInfo = {{
    {"NOP", 1, 4, 4, "----"},  // 0x00
    {"LD BC, n16", 3, 12, 12, "----"},  // 0x01
    {"LD [BC], A", 1, 8, 8, "----"},  // 0x02
    {"INC BC", 1, 8, 8, "----"},  // 0x03
    {"INC B", 1, 4, 4, "Z0H-"},  // 0x04
    {"DEC B", 1, 4, 4, "Z1H-"},  // 0x05
    {"LD B, n8", 2, 8, 8, "----"},  // 0x06
    {"RLCA", 1, 4, 4, "000C"},  // 0x07
    {"LD [a16], SP", 3, 20, 20, "----"},  // 0x08
    {"ADD HL, BC", 1, 8, 8, "-0HC"},  // 0x09
    {"LD A, [BC]", 1, 8, 8, "----"},  // 0x0A
    {"DEC BC", 1, 8, 8, "----"},  // 0x0B
    {"INC C", 1, 4, 4, "Z0H-"},  // 0x0C
    {"DEC C", 1, 4, 4, "Z1H-"},  // 0x0D
    {"LD C, n8", 2, 8, 8, "----"},  // 0x0E
    {"RRCA", 1, 4, 4, "000C"},  // 0x0F
    {"STOP n8", 2, 4, 4, "----"},  // 0x10
    {"LD DE, n16", 3, 12, 12, "----"},  // 0x11
    {"LD [DE], A", 1, 8, 8, "----"},  // 0x12
    {"INC DE", 1, 8, 8, "----"},  // 0x13
    {"INC D", 1, 4, 4, "Z0H-"},  // 0x14
    {"DEC D", 1, 4, 4, "Z1H-"},  // 0x15
    {"LD D, n8", 2, 8, 8, "----"},  // 0x16
    {"RLA", 1, 4, 4, "000C"},  // 0x17
    {"JR e8", 2, 12, 12, "----"},  // 0x18
    {"ADD HL, DE", 1, 8, 8, "-0HC"},  // 0x19
    {"LD A, [DE]", 1, 8, 8, "----"},  // 0x1A
    {"DEC DE", 1, 8, 8, "----"},  // 0x1B
    {"INC E", 1, 4, 4, "Z0H-"},  // 0x1C
    {"DEC E", 1, 4, 4, "Z1H-"},  // 0x1D
    {"LD E, n8", 2, 8, 8, "----"},  // 0x1E
    {"RRA", 1, 4, 4, "000C"},  // 0x1F
    {"JR NZ, e8", 2, 12, 8, "----"},  // 0x20
    {"LD HL, n16", 3, 12, 12, "----"},  // 0x21
    {"LD [HL+], A", 1, 8, 8, "----"},  // 0x22
    {"INC HL", 1, 8, 8, "----"},  // 0x23
    {"INC H", 1, 4, 4, "Z0H-"},  // 0x24
    {"DEC H", 1, 4, 4, "Z1H-"},  // 0x25
    {"LD H, n8", 2, 8, 8, "----"},  // 0x26
    {"DAA", 1, 4, 4, "Z-0C"},  // 0x27
    {"JR Z, e8", 2, 12, 8, "----"},  // 0x28
    {"ADD HL, HL", 1, 8, 8, "-0HC"},  // 0x29
    {"LD A, [HL+]", 1, 8, 8, "----"},  // 0x2A
    {"DEC HL", 1, 8, 8, "----"},  // 0x2B
    {"INC L", 1, 4, 4, "Z0H-"},  // 0x2C
    {"DEC L", 1, 4, 4, "Z1H-"},  // 0x2D
    {"LD L, n8", 2, 8, 8, "----"},  // 0x2E
    {"CPL", 1, 4, 4, "-11-"},  // 0x2F
    {"JR NC, e8", 2, 12, 8, "----"},  // 0x30
    {"LD SP, n16", 3, 12, 12, "----"},  // 0x31
    {"LD [HL-], A", 1, 8, 8, "----"},  // 0x32
    {"INC SP", 1, 8, 8, "----"},  // 0x33
    {"INC [HL]", 1, 12, 12, "Z0H-"},  // 0x34
    {"DEC [HL]", 1, 12, 12, "Z1H-"},  // 0x35
    {"LD [HL], n8", 2, 12, 12, "----"},  // 0x36
    {"SCF", 1, 4, 4, "-001"},  // 0x37
    {"JR C, e8", 2, 12, 8, "----"},  // 0x38
    {"ADD HL, SP", 1, 8, 8, "-0HC"},  // 0x39
    {"LD A, [HL-]", 1, 8, 8, "----"},  // 0x3A
    {"DEC SP", 1, 8, 8, "----"},  // 0x3B
    {"INC A", 1, 4, 4, "Z0H-"},  // 0x3C
    {"DEC A", 1, 4, 4, "Z1H-"},  // 0x3D
    {"LD A, n8", 2, 8, 8, "----"},  // 0x3E
    {"CCF", 1, 4, 4, "-00C"},  // 0x3F
    {"LD B, B", 1, 4, 4, "----"},  // 0x40
    {"LD B, C", 1, 4, 4, "----"},  // 0x41
    {"LD B, D", 1, 4, 4, "----"},  // 0x42
    {"LD B, E", 1, 4, 4, "----"},  // 0x43
    {"LD B, H", 1, 4, 4, "----"},  // 0x44
    {"LD B, L", 1, 4, 4, "----"},  // 0x45
    {"LD B, [HL]", 1, 8, 8, "----"},  // 0x46
    {"LD B, A", 1, 4, 4, "----"},  // 0x47
    {"LD C, B", 1, 4, 4, "----"},  // 0x48
    {"LD C, C", 1, 4, 4, "----"},  // 0x49
    {"LD C, D", 1, 4, 4, "----"},  // 0x4A
    {"LD C, E", 1, 4, 4, "----"},  // 0x4B
    {"LD C, H", 1, 4, 4, "----"},  // 0x4C
    {"LD C, L", 1, 4, 4, "----"},  // 0x4D
    {"LD C, [HL]", 1, 8, 8, "----"},  // 0x4E
    {"LD C, A", 1, 4, 4, "----"},  // 0x4F
    {"LD D, B", 1, 4, 4, "----"},  // 0x50
    {"LD D, C", 1, 4, 4, "----"},  // 0x51
    {"LD D, D", 1, 4, 4, "----"},  // 0x52
    {"LD D, E", 1, 4, 4, "----"},  // 0x53
    {"LD D, H", 1, 4, 4, "----"},  // 0x54
    {"LD D, L", 1, 4, 4, "----"},  // 0x55
    {"LD D, [HL]", 1, 8, 8, "----"},  // 0x56
    {"LD D, A", 1, 4, 4, "----"},  // 0x57
    {"LD E, B", 1, 4, 4, "----"},  // 0x58
    {"LD E, C", 1, 4, 4, "----"},  // 0x59
    {"LD E, D", 1, 4, 4, "----"},  // 0x5A
    {"LD E, E", 1, 4, 4, "----"},  // 0x5B
    {"LD E, H", 1, 4, 4, "----"},  // 0x5C
    {"LD E, L", 1, 4, 4, "----"},  // 0x5D
    {"LD E, [HL]", 1, 8, 8, "----"},  // 0x5E
    {"LD E, A", 1, 4, 4, "----"},  // 0x5F
    {"LD H, B", 1, 4, 4, "----"},  // 0x60
    {"LD H, C", 1, 4, 4, "----"},  // 0x61
    {"LD H, D", 1, 4, 4, "----"},  // 0x62
    {"LD H, E", 1, 4, 4, "----"},  // 0x63
    {"LD H, H", 1, 4, 4, "----"},  // 0x64
    {"LD H, L", 1, 4, 4, "----"},  // 0x65
    {"LD H, [HL]", 1, 8, 8, "----"},  // 0x66
    {"LD H, A", 1, 4, 4, "----"},  // 0x67
    {"LD L, B", 1, 4, 4, "----"},  // 0x68
    {"LD L, C", 1, 4, 4, "----"},  // 0x69
    {"LD L, D", 1, 4, 4, "----"},  // 0x6A
    {"LD L, E", 1, 4, 4, "----"},  // 0x6B
    {"LD L, H", 1, 4, 4, "----"},  // 0x6C
    {"LD L, L", 1, 4, 4, "----"},  // 0x6D
    {"LD L, [HL]", 1, 8, 8, "----"},  // 0x6E
    {"LD L, A", 1, 4, 4, "----"},  // 0x6F
    {"LD [HL], B", 1, 8, 8, "----"},  // 0x70
    {"LD [HL], C", 1, 8, 8, "----"},  // 0x71
    {"LD [HL], D", 1, 8, 8, "----"},  // 0x72
    {"LD [HL], E", 1, 8, 8, "----"},  // 0x73
    {"LD [HL], H", 1, 8, 8, "----"},  // 0x74
    {"LD [HL], L", 1, 8, 8, "----"},  // 0x75
    {"HALT", 1, 4, 4, "----"},  // 0x76
    {"LD [HL], A", 1, 8, 8, "----"},  // 0x77
    {"LD A, B", 1, 4, 4, "----"},  // 0x78
    {"LD A, C", 1, 4, 4, "----"},  // 0x79
    {"LD A, D", 1, 4, 4, "----"},  // 0x7A
    {"LD A, E", 1, 4, 4, "----"},  // 0x7B
    {"LD A, H", 1, 4, 4, "----"},  // 0x7C
    {"LD A, L", 1, 4, 4, "----"},  // 0x7D
    {"LD A, [HL]", 1, 8, 8, "----"},  // 0x7E
    {"LD A, A", 1, 4, 4, "----"},  // 0x7F
    {"ADD A, B", 1, 4, 4, "Z0HC"},  // 0x80
    {"ADD A, C", 1, 4, 4, "Z0HC"},  // 0x81
    {"ADD A, D", 1, 4, 4, "Z0HC"},  // 0x82
    {"ADD A, E", 1, 4, 4, "Z0HC"},  // 0x83
    {"ADD A, H", 1, 4, 4, "Z0HC"},  // 0x84
    {"ADD A, L", 1, 4, 4, "Z0HC"},  // 0x85
    {"ADD A, [HL]", 1, 8, 8, "Z0HC"},  // 0x86
    {"ADD A, A", 1, 4, 4, "Z0HC"},  // 0x87
    {"ADC A, B", 1, 4, 4, "Z0HC"},  // 0x88
    {"ADC A, C", 1, 4, 4, "Z0HC"},  // 0x89
    {"ADC A, D", 1, 4, 4, "Z0HC"},  // 0x8A
    {"ADC A, E", 1, 4, 4, "Z0HC"},  // 0x8B
    {"ADC A, H", 1, 4, 4, "Z0HC"},  // 0x8C
    {"ADC A, L", 1, 4, 4, "Z0HC"},  // 0x8D
    {"ADC A, [HL]", 1, 8, 8, "Z0HC"},  // 0x8E
    {"ADC A, A", 1, 4, 4, "Z0HC"},  // 0x8F
    {"SUB A, B", 1, 4, 4, "Z1HC"},  // 0x90
    {"SUB A, C", 1, 4, 4, "Z1HC"},  // 0x91
    {"SUB A, D", 1, 4, 4, "Z1HC"},  // 0x92
    {"SUB A, E", 1, 4, 4, "Z1HC"},  // 0x93
    {"SUB A, H", 1, 4, 4, "Z1HC"},  // 0x94
    {"SUB A, L", 1, 4, 4, "Z1HC"},  // 0x95
    {"SUB A, [HL]", 1, 8, 8, "Z1HC"},  // 0x96
    {"SUB A, A", 1, 4, 4, "1100"},  // 0x97
    {"SBC A, B", 1, 4, 4, "Z1HC"},  // 0x98
    {"SBC A, C", 1, 4, 4, "Z1HC"},  // 0x99
    {"SBC A, D", 1, 4, 4, "Z1HC"},  // 0x9A
    {"SBC A, E", 1, 4, 4, "Z1HC"},  // 0x9B
    {"SBC A, H", 1, 4, 4, "Z1HC"},  // 0x9C
    {"SBC A, L", 1, 4, 4, "Z1HC"},  // 0x9D
    {"SBC A, [HL]", 1, 8, 8, "Z1HC"},  // 0x9E
    {"SBC A, A", 1, 4, 4, "Z1H-"},  // 0x9F
    {"AND A, B", 1, 4, 4, "Z010"},  // 0xA0
    {"AND A, C", 1, 4, 4, "Z010"},  // 0xA1
    {"AND A, D", 1, 4, 4, "Z010"},  // 0xA2
    {"AND A, E", 1, 4, 4, "Z010"},  // 0xA3
    {"AND A, H", 1, 4, 4, "Z010"},  // 0xA4
    {"AND A, L", 1, 4, 4, "Z010"},  // 0xA5
    {"AND A, [HL]", 1, 8, 8, "Z010"},  // 0xA6
    {"AND A, A", 1, 4, 4, "Z010"},  // 0xA7
    {"XOR A, B", 1, 4, 4, "Z000"},  // 0xA8
    {"XOR A, C", 1, 4, 4, "Z000"},  // 0xA9
    {"XOR A, D", 1, 4, 4, "Z000"},  // 0xAA
    {"XOR A, E", 1, 4, 4, "Z000"},  // 0xAB
    {"XOR A, H", 1, 4, 4, "Z000"},  // 0xAC
    {"XOR A, L", 1, 4, 4, "Z000"},  // 0xAD
    {"XOR A, [HL]", 1, 8, 8, "Z000"},  // 0xAE
    {"XOR A, A", 1, 4, 4, "1000"},  // 0xAF
    {"OR A, B", 1, 4, 4, "Z000"},  // 0xB0
    {"OR A, C", 1, 4, 4, "Z000"},  // 0xB1
    {"OR A, D", 1, 4, 4, "Z000"},  // 0xB2
    {"OR A, E", 1, 4, 4, "Z000"},  // 0xB3
    {"OR A, H", 1, 4, 4, "Z000"},  // 0xB4
    {"OR A, L", 1, 4, 4, "Z000"},  // 0xB5
    {"OR A, [HL]", 1, 8, 8, "Z000"},  // 0xB6
    {"OR A, A", 1, 4, 4, "Z000"},  // 0xB7
    {"CP A, B", 1, 4, 4, "Z1HC"},  // 0xB8
    {"CP A, C", 1, 4, 4, "Z1HC"},  // 0xB9
    {"CP A, D", 1, 4, 4, "Z1HC"},  // 0xBA
    {"CP A, E", 1, 4, 4, "Z1HC"},  // 0xBB
    {"CP A, H", 1, 4, 4, "Z1HC"},  // 0xBC
    {"CP A, L", 1, 4, 4, "Z1HC"},  // 0xBD
    {"CP A, [HL]", 1, 8, 8, "Z1HC"},  // 0xBE
    {"CP A, A", 1, 4, 4, "1100"},  // 0xBF
    {"RET NZ", 1, 20, 8, "----"},  // 0xC0
    {"POP BC", 1, 12, 12, "----"},  // 0xC1
    {"JP NZ, a16", 3, 16, 12, "----"},  // 0xC2
    {"JP a16", 3, 16, 16, "----"},  // 0xC3
    {"CALL NZ, a16", 3, 24, 12, "----"},  // 0xC4
    {"PUSH BC", 1, 16, 16, "----"},  // 0xC5
    {"ADD A, n8", 2, 8, 8, "Z0HC"},  // 0xC6
    {"RST $00", 1, 16, 16, "----"},  // 0xC7
    {"RET Z", 1, 20, 8, "----"},  // 0xC8
    {"RET", 1, 16, 16, "----"},  // 0xC9
    {"JP Z, a16", 3, 16, 12, "----"},  // 0xCA
    {"PREFIX", 1, 4, 4, "----"},  // 0xCB
    {"CALL Z, a16", 3, 24, 12, "----"},  // 0xCC
    {"CALL a16", 3, 24, 24, "----"},  // 0xCD
    {"ADC A, n8", 2, 8, 8, "Z0HC"},  // 0xCE
    {"RST $08", 1, 16, 16, "----"},  // 0xCF
    {"RET NC", 1, 20, 8, "----"},  // 0xD0
    {"POP DE", 1, 12, 12, "----"},  // 0xD1
    {"JP NC, a16", 3, 16, 12, "----"},  // 0xD2
    {"ILLEGAL", 1, 4, 4, "----"},  // 0xD3
    {"CALL NC, a16", 3, 24, 12, "----"},  // 0xD4
    {"PUSH DE", 1, 16, 16, "----"},  // 0xD5
    {"SUB A, n8", 2, 8, 8, "Z1HC"},  // 0xD6
    {"RST $10", 1, 16, 16, "----"},  // 0xD7
    {"RET C", 1, 20, 8, "----"},  // 0xD8
    {"RETI", 1, 16, 16, "----"},  // 0xD9
    {"JP C, a16", 3, 16, 12, "----"},  // 0xDA
    {"ILLEGAL", 1, 4, 4, "----"},  // 0xDB
    {"CALL C, a16", 3, 24, 12, "----"},  // 0xDC
    {"ILLEGAL", 1, 4, 4, "----"},  // 0xDD
    {"SBC A, n8", 2, 8, 8, "Z1HC"},  // 0xDE
    {"RST $18", 1, 16, 16, "----"},  // 0xDF
    {"LDH [a8], A", 2, 12, 12, "----"},  // 0xE0
    {"POP HL", 1, 12, 12, "----"},  // 0xE1
    {"LDH [C], A", 1, 8, 8, "----"},  // 0xE2
    {"ILLEGAL", 1, 4, 4, "----"},  // 0xE3
    {"ILLEGAL", 1, 4, 4, "----"},  // 0xE4
    {"PUSH HL", 1, 16, 16, "----"},  // 0xE5
    {"AND A, n8", 2, 8, 8, "Z010"},  // 0xE6
    {"RST $20", 1, 16, 16, "----"},  // 0xE7
    {"ADD SP, e8", 2, 16, 16, "00HC"},  // 0xE8
    {"JP HL", 1, 4, 4, "----"},  // 0xE9
    {"LD [a16], A", 3, 16, 16, "----"},  // 0xEA
    {"ILLEGAL", 1, 4, 4, "----"},  // 0xEB
    {"ILLEGAL", 1, 4, 4, "----"},  // 0xEC
    {"ILLEGAL", 1, 4, 4, "----"},  // 0xED
    {"XOR A, n8", 2, 8, 8, "Z000"},  // 0xEE
    {"RST $28", 1, 16, 16, "----"},  // 0xEF
    {"LDH A, [a8]", 2, 12, 12, "----"},  // 0xF0
    {"POP AF", 1, 12, 12, "ZNHC"},  // 0xF1
    {"LDH A, [C]", 1, 8, 8, "----"},  // 0xF2
    {"DI", 1, 4, 4, "----"},  // 0xF3
    {"ILLEGAL", 1, 4, 4, "----"},  // 0xF4
    {"PUSH AF", 1, 16, 16, "----"},  // 0xF5
    {"OR A, n8", 2, 8, 8, "Z000"},  // 0xF6
    {"RST $30", 1, 16, 16, "----"},  // 0xF7
    {"LD HL, SP+e8", 2, 12, 12, "00HC"},  // 0xF8
    {"LD SP, HL", 1, 8, 8, "----"},  // 0xF9
    {"LD A, [a16]", 3, 16, 16, "----"},  // 0xFA
    {"EI", 1, 4, 4, "----"},  // 0xFB
    {"ILLEGAL", 1, 4, 4, "----"},  // 0xFC
    {"ILLEGAL", 1, 4, 4, "----"},  // 0xFD
    {"CP A, n8", 2, 8, 8, "Z1HC"},  // 0xFE
    {"RST $38", 1, 16, 16, "----"},  // 0xFF
}};

const std::array<OpcodeInfo, 256> kCbOpcodeInfo = {{
    {"RLC B", 2, 8, 8, "Z00C"},  // 0x00
    {"RLC C", 2, 8, 8, "Z00C"},  // 0x01
    {"RLC D", 2, 8, 8, "Z00C"},  // 0x02
    {"RLC E", 2, 8, 8, "Z00C"},  // 0x03
    {"RLC H", 2, 8, 8, "Z00C"},  // 0x04
    {"RLC L", 2, 8, 8, "Z00C"},  // 0x05
    {"RLC [HL]", 2, 16, 16, "Z00C"},  // 0x06
    {"RLC A", 2, 8, 8, "Z00C"},  // 0x07
    {"RRC B", 2, 8, 8, "Z00C"},  // 0x08
    {"RRC C", 2, 8, 8, "Z00C"},  // 0x09
    {"RRC D", 2, 8, 8, "Z00C"},  // 0x0A
    {"RRC E", 2, 8, 8, "Z00C"},  // 0x0B
    {"RRC H", 2, 8, 8, "Z00C"},  // 0x0C
    {"RRC L", 2, 8, 8, "Z00C"},  // 0x0D
    {"RRC [HL]", 2, 16, 16, "Z00C"},  // 0x0E
    {"RRC A", 2, 8, 8, "Z00C"},  // 0x0F
    {"RL B", 2, 8, 8, "Z00C"},  // 0x10
    {"RL C", 2, 8, 8, "Z00C"},  // 0x11
    {"RL D", 2, 8, 8, "Z00C"},  // 0x12
    {"RL E", 2, 8, 8, "Z00C"},  // 0x13
    {"RL H", 2, 8, 8, "Z00C"},  // 0x14
    {"RL L", 2, 8, 8, "Z00C"},  // 0x15
    {"RL [HL]", 2, 16, 16, "Z00C"},  // 0x16
    {"RL A", 2, 8, 8, "Z00C"},  // 0x17
    {"RR B", 2, 8, 8, "Z00C"},  // 0x18
    {"RR C", 2, 8, 8, "Z00C"},  // 0x19
    {"RR D", 2, 8, 8, "Z00C"},  // 0x1A
    {"RR E", 2, 8, 8, "Z00C"},  // 0x1B
    {"RR H", 2, 8, 8, "Z00C"},  // 0x1C
    {"RR L", 2, 8, 8, "Z00C"},  // 0x1D
    {"RR [HL]", 2, 16, 16, "Z00C"},  // 0x1E
    {"RR A", 2, 8, 8, "Z00C"},  // 0x1F
    {"SLA B", 2, 8, 8, "Z00C"},  // 0x20
    {"SLA C", 2, 8, 8, "Z00C"},  // 0x21
    {"SLA D", 2, 8, 8, "Z00C"},  // 0x22
    {"SLA E", 2, 8, 8, "Z00C"},  // 0x23
    {"SLA H", 2, 8, 8, "Z00C"},  // 0x24
    {"SLA L", 2, 8, 8, "Z00C"},  // 0x25
    {"SLA [HL]", 2, 16, 16, "Z00C"},  // 0x26
    {"SLA A", 2, 8, 8, "Z00C"},  // 0x27
    {"SRA B", 2, 8, 8, "Z00C"},  // 0x28
    {"SRA C", 2, 8, 8, "Z00C"},  // 0x29
    {"SRA D", 2, 8, 8, "Z00C"},  // 0x2A
    {"SRA E", 2, 8, 8, "Z00C"},  // 0x2B
    {"SRA H", 2, 8, 8, "Z00C"},  // 0x2C
    {"SRA L", 2, 8, 8, "Z00C"},  // 0x2D
    {"SRA [HL]", 2, 16, 16, "Z00C"},  // 0x2E
    {"SRA A", 2, 8, 8, "Z00C"},  // 0x2F
    {"SWAP B", 2, 8, 8, "Z000"},  // 0x30
    {"SWAP C", 2, 8, 8, "Z000"},  // 0x31
    {"SWAP D", 2, 8, 8, "Z000"},  // 0x32
    {"SWAP E", 2, 8, 8, "Z000"},  // 0x33
    {"SWAP H", 2, 8, 8, "Z000"},  // 0x34
    {"SWAP L", 2, 8, 8, "Z000"},  // 0x35
    {"SWAP [HL]", 2, 16, 16, "Z000"},  // 0x36
    {"SWAP A", 2, 8, 8, "Z000"},  // 0x37
    {"SRL B", 2, 8, 8, "Z00C"},  // 0x38
    {"SRL C", 2, 8, 8, "Z00C"},  // 0x39
    {"SRL D", 2, 8, 8, "Z00C"},  // 0x3A
    {"SRL E", 2, 8, 8, "Z00C"},  // 0x3B
    {"SRL H", 2, 8, 8, "Z00C"},  // 0x3C
    {"SRL L", 2, 8, 8, "Z00C"},  // 0x3D
    {"SRL [HL]", 2, 16, 16, "Z00C"},  // 0x3E
    {"SRL A", 2, 8, 8, "Z00C"},  // 0x3F
    {"BIT 0, B", 2, 8, 8, "Z01-"},  // 0x40
    {"BIT 0, C", 2, 8, 8, "Z01-"},  // 0x41
    {"BIT 0, D", 2, 8, 8, "Z01-"},  // 0x42
    {"BIT 0, E", 2, 8, 8, "Z01-"},  // 0x43
    {"BIT 0, H", 2, 8, 8, "Z01-"},  // 0x44
    {"BIT 0, L", 2, 8, 8, "Z01-"},  // 0x45
    {"BIT 0, [HL]", 2, 12, 12, "Z01-"},  // 0x46
    {"BIT 0, A", 2, 8, 8, "Z01-"},  // 0x47
    {"BIT 1, B", 2, 8, 8, "Z01-"},  // 0x48
    {"BIT 1, C", 2, 8, 8, "Z01-"},  // 0x49
    {"BIT 1, D", 2, 8, 8, "Z01-"},  // 0x4A
    {"BIT 1, E", 2, 8, 8, "Z01-"},  // 0x4B
    {"BIT 1, H", 2, 8, 8, "Z01-"},  // 0x4C
    {"BIT 1, L", 2, 8, 8, "Z01-"},  // 0x4D
    {"BIT 1, [HL]", 2, 12, 12, "Z01-"},  // 0x4E
    {"BIT 1, A", 2, 8, 8, "Z01-"},  // 0x4F
    {"BIT 2, B", 2, 8, 8, "Z01-"},  // 0x50
    {"BIT 2, C", 2, 8, 8, "Z01-"},  // 0x51
    {"BIT 2, D", 2, 8, 8, "Z01-"},  // 0x52
    {"BIT 2, E", 2, 8, 8, "Z01-"},  // 0x53
    {"BIT 2, H", 2, 8, 8, "Z01-"},  // 0x54
    {"BIT 2, L", 2, 8, 8, "Z01-"},  // 0x55
    {"BIT 2, [HL]", 2, 12, 12, "Z01-"},  // 0x56
    {"BIT 2, A", 2, 8, 8, "Z01-"},  // 0x57
    {"BIT 3, B", 2, 8, 8, "Z01-"},  // 0x58
    {"BIT 3, C", 2, 8, 8, "Z01-"},  // 0x59
    {"BIT 3, D", 2, 8, 8, "Z01-"},  // 0x5A
    {"BIT 3, E", 2, 8, 8, "Z01-"},  // 0x5B
    {"BIT 3, H", 2, 8, 8, "Z01-"},  // 0x5C
    {"BIT 3, L", 2, 8, 8, "Z01-"},  // 0x5D
    {"BIT 3, [HL]", 2, 12, 12, "Z01-"},  // 0x5E
    {"BIT 3, A", 2, 8, 8, "Z01-"},  // 0x5F
    {"BIT 4, B", 2, 8, 8, "Z01-"},  // 0x60
    {"BIT 4, C", 2, 8, 8, "Z01-"},  // 0x61
    {"BIT 4, D", 2, 8, 8, "Z01-"},  // 0x62
    {"BIT 4, E", 2, 8, 8, "Z01-"},  // 0x63
    {"BIT 4, H", 2, 8, 8, "Z01-"},  // 0x64
    {"BIT 4, L", 2, 8, 8, "Z01-"},  // 0x65
    {"BIT 4, [HL]", 2, 12, 12, "Z01-"},  // 0x66
    {"BIT 4, A", 2, 8, 8, "Z01-"},  // 0x67
    {"BIT 5, B", 2, 8, 8, "Z01-"},  // 0x68
    {"BIT 5, C", 2, 8, 8, "Z01-"},  // 0x69
    {"BIT 5, D", 2, 8, 8, "Z01-"},  // 0x6A
    {"BIT 5, E", 2, 8, 8, "Z01-"},  // 0x6B
    {"BIT 5, H", 2, 8, 8, "Z01-"},  // 0x6C
    {"BIT 5, L", 2, 8, 8, "Z01-"},  // 0x6D
    {"BIT 5, [HL]", 2, 12, 12, "Z01-"},  // 0x6E
    {"BIT 5, A", 2, 8, 8, "Z01-"},  // 0x6F
    {"BIT 6, B", 2, 8, 8, "Z01-"},  // 0x70
    {"BIT 6, C", 2, 8, 8, "Z01-"},  // 0x71
    {"BIT 6, D", 2, 8, 8, "Z01-"},  // 0x72
    {"BIT 6, E", 2, 8, 8, "Z01-"},  // 0x73
    {"BIT 6, H", 2, 8, 8, "Z01-"},  // 0x74
    {"BIT 6, L", 2, 8, 8, "Z01-"},  // 0x75
    {"BIT 6, [HL]", 2, 12, 12, "Z01-"},  // 0x76
    {"BIT 6, A", 2, 8, 8, "Z01-"},  // 0x77
    {"BIT 7, B", 2, 8, 8, "Z01-"},  // 0x78
    {"BIT 7, C", 2, 8, 8, "Z01-"},  // 0x79
    {"BIT 7, D", 2, 8, 8, "Z01-"},  // 0x7A
    {"BIT 7, E", 2, 8, 8, "Z01-"},  // 0x7B
    {"BIT 7, H", 2, 8, 8, "Z01-"},  // 0x7C
    {"BIT 7, L", 2, 8, 8, "Z01-"},  // 0x7D
    {"BIT 7, [HL]", 2, 12, 12, "Z01-"},  // 0x7E
    {"BIT 7, A", 2, 8, 8, "Z01-"},  // 0x7F
    {"RES 0, B", 2, 8, 8, "----"},  // 0x80
    {"RES 0, C", 2, 8, 8, "----"},  // 0x81
    {"RES 0, D", 2, 8, 8, "----"},  // 0x82
    {"RES 0, E", 2, 8, 8, "----"},  // 0x83
    {"RES 0, H", 2, 8, 8, "----"},  // 0x84
    {"RES 0, L", 2, 8, 8, "----"},  // 0x85
    {"RES 0, [HL]", 2, 16, 16, "----"},  // 0x86
    {"RES 0, A", 2, 8, 8, "----"},  // 0x87
    {"RES 1, B", 2, 8, 8, "----"},  // 0x88
    {"RES 1, C", 2, 8, 8, "----"},  // 0x89
    {"RES 1, D", 2, 8, 8, "----"},  // 0x8A
    {"RES 1, E", 2, 8, 8, "----"},  // 0x8B
    {"RES 1, H", 2, 8, 8, "----"},  // 0x8C
    {"RES 1, L", 2, 8, 8, "----"},  // 0x8D
    {"RES 1, [HL]", 2, 16, 16, "----"},  // 0x8E
    {"RES 1, A", 2, 8, 8, "----"},  // 0x8F
    {"RES 2, B", 2, 8, 8, "----"},  // 0x90
    {"RES 2, C", 2, 8, 8, "----"},  // 0x91
    {"RES 2, D", 2, 8, 8, "----"},  // 0x92
    {"RES 2, E", 2, 8, 8, "----"},  // 0x93
    {"RES 2, H", 2, 8, 8, "----"},  // 0x94
    {"RES 2, L", 2, 8, 8, "----"},  // 0x95
    {"RES 2, [HL]", 2, 16, 16, "----"},  // 0x96
    {"RES 2, A", 2, 8, 8, "----"},  // 0x97
    {"RES 3, B", 2, 8, 8, "----"},  // 0x98
    {"RES 3, C", 2, 8, 8, "----"},  // 0x99
    {"RES 3, D", 2, 8, 8, "----"},  // 0x9A
    {"RES 3, E", 2, 8, 8, "----"},  // 0x9B
    {"RES 3, H", 2, 8, 8, "----"},  // 0x9C
    {"RES 3, L", 2, 8, 8, "----"},  // 0x9D
    {"RES 3, [HL]", 2, 16, 16, "----"},  // 0x9E
    {"RES 3, A", 2, 8, 8, "----"},  // 0x9F
    {"RES 4, B", 2, 8, 8, "----"},  // 0xA0
    {"RES 4, C", 2, 8, 8, "----"},  // 0xA1
    {"RES 4, D", 2, 8, 8, "----"},  // 0xA2
    {"RES 4, E", 2, 8, 8, "----"},  // 0xA3
    {"RES 4, H", 2, 8, 8, "----"},  // 0xA4
    {"RES 4, L", 2, 8, 8, "----"},  // 0xA5
    {"RES 4, [HL]", 2, 16, 16, "----"},  // 0xA6
    {"RES 4, A", 2, 8, 8, "----"},  // 0xA7
    {"RES 5, B", 2, 8, 8, "----"},  // 0xA8
    {"RES 5, C", 2, 8, 8, "----"},  // 0xA9
    {"RES 5, D", 2, 8, 8, "----"},  // 0xAA
    {"RES 5, E", 2, 8, 8, "----"},  // 0xAB
    {"RES 5, H", 2, 8, 8, "----"},  // 0xAC
    {"RES 5, L", 2, 8, 8, "----"},  // 0xAD
    {"RES 5, [HL]", 2, 16, 16, "----"},  // 0xAE
    {"RES 5, A", 2, 8, 8, "----"},  // 0xAF
    {"RES 6, B", 2, 8, 8, "----"},  // 0xB0
    {"RES 6, C", 2, 8, 8, "----"},  // 0xB1
    {"RES 6, D", 2, 8, 8, "----"},  // 0xB2
    {"RES 6, E", 2, 8, 8, "----"},  // 0xB3
    {"RES 6, H", 2, 8, 8, "----"},  // 0xB4
    {"RES 6, L", 2, 8, 8, "----"},  // 0xB5
    {"RES 6, [HL]", 2, 16, 16, "----"},  // 0xB6
    {"RES 6, A", 2, 8, 8, "----"},  // 0xB7
    {"RES 7, B", 2, 8, 8, "----"},  // 0xB8
    {"RES 7, C", 2, 8, 8, "----"},  // 0xB9
    {"RES 7, D", 2, 8, 8, "----"},  // 0xBA
    {"RES 7, E", 2, 8, 8, "----"},  // 0xBB
    {"RES 7, H", 2, 8, 8, "----"},  // 0xBC
    {"RES 7, L", 2, 8, 8, "----"},  // 0xBD
    {"RES 7, [HL]", 2, 16, 16, "----"},  // 0xBE
    {"RES 7, A", 2, 8, 8, "----"},  // 0xBF
    {"SET 0, B", 2, 8, 8, "----"},  // 0xC0
    {"SET 0, C", 2, 8, 8, "----"},  // 0xC1
    {"SET 0, D", 2, 8, 8, "----"},  // 0xC2
    {"SET 0, E", 2, 8, 8, "----"},  // 0xC3
    {"SET 0, H", 2, 8, 8, "----"},  // 0xC4
    {"SET 0, L", 2, 8, 8, "----"},  // 0xC5
    {"SET 0, [HL]", 2, 16, 16, "----"},  // 0xC6
    {"SET 0, A", 2, 8, 8, "----"},  // 0xC7
    {"SET 1, B", 2, 8, 8, "----"},  // 0xC8
    {"SET 1, C", 2, 8, 8, "----"},  // 0xC9
    {"SET 1, D", 2, 8, 8, "----"},  // 0xCA
    {"SET 1, E", 2, 8, 8, "----"},  // 0xCB
    {"SET 1, H", 2, 8, 8, "----"},  // 0xCC
    {"SET 1, L", 2, 8, 8, "----"},  // 0xCD
    {"SET 1, [HL]", 2, 16, 16, "----"},  // 0xCE
    {"SET 1, A", 2, 8, 8, "----"},  // 0xCF
    {"SET 2, B", 2, 8, 8, "----"},  // 0xD0
    {"SET 2, C", 2, 8, 8, "----"},  // 0xD1
    {"SET 2, D", 2, 8, 8, "----"},  // 0xD2
    {"SET 2, E", 2, 8, 8, "----"},  // 0xD3
    {"SET 2, H", 2, 8, 8, "----"},  // 0xD4
    {"SET 2, L", 2, 8, 8, "----"},  // 0xD5
    {"SET 2, [HL]", 2, 16, 16, "----"},  // 0xD6
    {"SET 2, A", 2, 8, 8, "----"},  // 0xD7
    {"SET 3, B", 2, 8, 8, "----"},  // 0xD8
    {"SET 3, C", 2, 8, 8, "----"},  // 0xD9
    {"SET 3, D", 2, 8, 8, "----"},  // 0xDA
    {"SET 3, E", 2, 8, 8, "----"},  // 0xDB
    {"SET 3, H", 2, 8, 8, "----"},  // 0xDC
    {"SET 3, L", 2, 8, 8, "----"},  // 0xDD
    {"SET 3, [HL]", 2, 16, 16, "----"},  // 0xDE
    {"SET 3, A", 2, 8, 8, "----"},  // 0xDF
    {"SET 4, B", 2, 8, 8, "----"},  // 0xE0
    {"SET 4, C", 2, 8, 8, "----"},  // 0xE1
    {"SET 4, D", 2, 8, 8, "----"},  // 0xE2
    {"SET 4, E", 2, 8, 8, "----"},  // 0xE3
    {"SET 4, H", 2, 8, 8, "----"},  // 0xE4
    {"SET 4, L", 2, 8, 8, "----"},  // 0xE5
    {"SET 4, [HL]", 2, 16, 16, "----"},  // 0xE6
    {"SET 4, A", 2, 8, 8, "----"},  // 0xE7
    {"SET 5, B", 2, 8, 8, "----"},  // 0xE8
    {"SET 5, C", 2, 8, 8, "----"},  // 0xE9
    {"SET 5, D", 2, 8, 8, "----"},  // 0xEA
    {"SET 5, E", 2, 8, 8, "----"},  // 0xEB
    {"SET 5, H", 2, 8, 8, "----"},  // 0xEC
    {"SET 5, L", 2, 8, 8, "----"},  // 0xED
    {"SET 5, [HL]", 2, 16, 16, "----"},  // 0xEE
    {"SET 5, A", 2, 8, 8, "----"},  // 0xEF
    {"SET 6, B", 2, 8, 8, "----"},  // 0xF0
    {"SET 6, C", 2, 8, 8, "----"},  // 0xF1
    {"SET 6, D", 2, 8, 8, "----"},  // 0xF2
    {"SET 6, E", 2, 8, 8, "----"},  // 0xF3
    {"SET 6, H", 2, 8, 8, "----"},  // 0xF4
    {"SET 6, L", 2, 8, 8, "----"},  // 0xF5
    {"SET 6, [HL]", 2, 16, 16, "----"},  // 0xF6
    {"SET 6, A", 2, 8, 8, "----"},  // 0xF7
    {"SET 7, B", 2, 8, 8, "----"},  // 0xF8
    {"SET 7, C", 2, 8, 8, "----"},  // 0xF9
    {"SET 7, D", 2, 8, 8, "----"},  // 0xFA
    {"SET 7, E", 2, 8, 8, "----"},  // 0xFB
    {"SET 7, H", 2, 8, 8, "----"},  // 0xFC
    {"SET 7, L", 2, 8, 8, "----"},  // 0xFD
    {"SET 7, [HL]", 2, 16, 16, "----"},  // 0xFE
    {"SET 7, A", 2, 8, 8, "----"},  // 0xFF
}};

}  // namespace core
